"""Generate ``template_map.py`` from Hevy's global exercise template catalog.

Hevy workouts carry a language-independent ``exercise_template_id`` for every
exercise. The built-in ``HEVY_TO_GARMIN`` map is keyed on the English exercise
name, so non-English users have to map everything by hand (#173). This script
joins Hevy's global template catalog (id -> English title) with that name map to
produce ``exercise_template_id -> (category, subcategory)``, which resolves in
any language.

Run after Hevy adds new exercises:

    HEVY_API_KEY=<key> python scripts/gen_template_map.py

Only NON-custom (global) templates are included, since custom template ids are
per-account and would not generalise.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import requests

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"
OUT = SRC / "hevy2garmin" / "template_map.py"
BASE = os.environ.get("HEVY_API_KEY_URL", "https://api.hevyapp.com/v1")


def fetch_templates(key: str) -> dict[str, str]:
    """Return {template_id: english_title} for all global Hevy templates."""
    headers = {"api-key": key}
    out: dict[str, str] = {}
    page = 1
    while True:
        resp = requests.get(
            f"{BASE}/exercise_templates",
            params={"page": page, "pageSize": 100},
            headers=headers,
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        for t in data.get("exercise_templates", []):
            if not t.get("is_custom") and t.get("id") and t.get("title"):
                out[t["id"]] = t["title"]
        if page >= data.get("page_count", page):
            break
        page += 1
    return out


def main() -> int:
    key = os.environ.get("HEVY_API_KEY")
    if not key:
        print("Set HEVY_API_KEY", file=sys.stderr)
        return 1

    sys.path.insert(0, str(SRC))
    from hevy2garmin.mapper import HEVY_TO_GARMIN

    templates = fetch_templates(key)
    mapped: dict[str, tuple[int, int]] = {}
    unmatched: list[str] = []
    for tid, title in templates.items():
        if title in HEVY_TO_GARMIN:
            mapped[tid] = HEVY_TO_GARMIN[title]
        else:
            unmatched.append(title)

    lines = [
        '"""Hevy ``exercise_template_id`` -> Garmin ``(category, subcategory)``.',
        "",
        "Auto-generated by ``scripts/gen_template_map.py``. Language-independent:",
        "the template id is the same regardless of the user's Hevy language (#173).",
        "Do not edit by hand; re-run the generator instead.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "TEMPLATE_TO_GARMIN: dict[str, tuple[int, int]] = {",
    ]
    for tid in sorted(mapped, key=lambda t: templates[t].lower()):
        cat, sub = mapped[tid]
        lines.append(f'    "{tid}": ({cat}, {sub}),  # {templates[tid]}')
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")

    print(f"global templates: {len(templates)}, mapped: {len(mapped)}, unmatched: {len(unmatched)}")
    print("wrote", OUT.relative_to(REPO))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
